#Bag of words



In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch dswithbrian",
                           "dswithbrian watch dswithbrian",
                           "people write comment",
                           "dswithbrian write comment"],"output":[1,1,0,0]})
df

text  output
0       people watch dswithbrian       1
1  dswithbrian watch dswithbrian       1
2           people write comment       0
3      dswithbrian write comment       0

In [3]:
#perform bag of words technique
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df["text"])


In [6]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbrian': 1, 'write': 4, 'comment': 0}


In [7]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

#N Grams

In [8]:
df = pd.DataFrame({"text":["people watch dswithbrian",
                           "dswithbrian watch dswithbrian",
                           "people write comment",
                           "dswithbrian write comment"],"output":[1,1,0,0]})
df

text  output
0       people watch dswithbrian       1
1  dswithbrian watch dswithbrian       1
2           people write comment       0
3      dswithbrian write comment       0

In [9]:
#BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [10]:
bow = cv.fit_transform(df["text"])

In [11]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbrian': 4, 'dswithbrian watch': 0, 'people write': 3, 'write comment': 5, 'dswithbrian write': 1}


In [12]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]
[[0 1 0 0 0 1]]


In [13]:
#Ti gram
# Bi grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [14]:
bow = cv.fit_transform(df["text"])

In [17]:
print(cv.vocabulary_)

{'people watch dswithbrian': 2, 'dswithbrian watch dswithbrian': 0, 'people write comment': 3, 'dswithbrian write comment': 1}


TF-IDF(Term frequency-Inverse document frequency)

In [18]:
df = pd.DataFrame({"text":["people watch dswithbrian",
                           "dswithbrian watch dswithbrian",
                           "people write comment",
                           "dswithbrian write comment"],"output":[1,1,0,0]})
df

text  output
0       people watch dswithbrian       1
1  dswithbrian watch dswithbrian       1
2           people write comment       0
3      dswithbrian write comment       0

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [25]:
arr = tfid.fit_transform(df["text"]).toarray()
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [26]:
print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
